var pluralize = require('pluralize')

let adjArr = [ 
  'Addicting','Afraid','Agreeable','Amused','Ancient','Angry','Annoyed','Anxious','Arrogant','Ashamed','Average','Awful','Bad','Beautiful','Better','Big','Bitter','Black','Blue','Boiling','Brave','Breezy','Brief','Bright','Broad','Broken','Bumpy','Calm','Careful','Charming','Cheerful','Chilly','Clumsy','Cold','Colossal','Combative','Comfortable','Confused','Cooing','Cool','Cooperative','Courageous','Crazy','Creepy','Cruel','Cuddly','Curly','Curved','Damp','Dangerous','Deafening','Deep','Defeated','Defiant','Delicious','Delightful','Depressed','Determined','Dirty','Disgusted','Disturbed','Dizzy','Dry','Dull','Dusty','Eager','Early','Elated','Embarrassed','Empty','Encouraging','Energetic','Enthusiastic','Envious','Evil','Excited','Exuberant','Faint','Fair','Faithful','Fantastic','Fast','Fat','Few','Fierce','Filthy','Fine','Flaky','Flat','Fluffy','Foolish','Forlorn','Frail','Frantic','Fresh','Friendly','Frightened','Funny','Fuzzy','Gentle','Giant','Gigantic','Good','Gorgeous','Greasy','Great','Green','Grieving','Grubby','Grumpy','Handsome','Happy','Hard','Harsh','Healthy','Heavy','Helpful','Helpless','High','Hilarious','Hissing','Hollow','Homeless','Horrible','Hot','Huge','Hungry','Hurt','Hushed','Husky','Icy','Ill','Immense','Itchy','Jealous','Jittery','Jolly','Juicy','Kind','Large','Late','Lazy','Light','Little','Lively','Lonely','Long','Loose','Loud','Lovely','Low','Lucky','Magnificent','Mammoth','Many','Massive','Melodic','Melted','Mighty','Miniature','Moaning','Modern','Mute','Mysterious','Narrow','Nasty','Naughty','Nervous','New','Nice','Nosy','Numerous','Nutty','Obedient','Obnoxious','Odd','Old','Orange','Ordinary','Outrageous','Panicky','Perfect','Petite','Plastic','Pleasant','Precious','Pretty','Prickly','Proud','Puny','Purple','Purring','Quaint','Quick','Quickest','Quiet','Rainy','Rapid','Rare','Raspy','Ratty','Red','Relieved','Repulsive','Resonant','Ripe','Roasted','Robust','Rotten','Rough','Round','Sad','Salty','Scary','Scattered','Scrawny','Screeching','Selfish','Shaggy','Shaky','Shallow','Sharp','Shivering','Short','Shrill','Silent','Silky','Silly','Skinny','Slimy','Slippery','Slow','Small','Smart','Smiling','Smooth','Soft','Solid','Sore','Sour','Spicy','Splendid','Spotty','Square','Squealing','Stale','Steady','Steep','Sticky','Stingy','Straight','Strange','Striped','Strong','Stupendous','Successful','Sweet','Swift','Tall','Tame','Tan','Tart','Tasteless','Tasty','Tender','Tender','Tense','Terrible','Testy','Thirsty','Thoughtful','Thoughtless','Thundering','Tight','Tiny','Tired','Tough','Tricky','Troubled','Ugliest','Ugly','Uneven','Upset','Uptight','Vast','Victorious','Vivacious','Voiceless','Wasteful','Watery','Weak','Weary','Wet','Whispering','Wicked','Wide','Wide-eyed','Witty','Wonderful','Wooden'
]

let animArr = [
    "Aardvark","Albatross","Alligator","Alpaca","Ant","Anteater","Antelope","Ape","Armadillo","Donkey","Baboon","Badger","Barracuda","Bat","Bear","Beaver","Bee","Bison","Boar","Buffalo","Butterfly","Camel","Capybara","Caribou","Cassowary","Cat","Caterpillar","Cattle","Chamois","Cheetah","Chicken","Chimpanzee","Chinchilla","Chough","Clam","Cobra","Cockroach","Cod","Cormorant","Coyote","Crab","Crane","Crocodile","Crow","Curlew","Deer","Dinosaur","Dog","Dogfish","Dolphin","Dotterel","Dove","Dragonfly","Duck","Dugong","Dunlin","Eagle","Echidna","Eel","Eland","Elephant","Elk","Emu","Falcon","Ferret","Finch","Fish","Flamingo","Fly","Fox","Frog","Gaur","Gazelle","Gerbil","Giraffe","Gnat","Gnu","Goat","Goldfinch","Goldfish","Goose","Gorilla","Goshawk","Grasshopper","Grouse","Guanaco","Gull","Hamster","Hare","Hawk","Hedgehog","Heron","Herring","Hippopotamus","Hornet","Horse","Human","Hummingbird","Hyena","Ibex","Ibis","Jackal","Jaguar","Jay","Jellyfish","Kangaroo","Kingfisher","Koala","Kookabura","Kouprey","Kudu","Lapwing","Lark","Lemur","Leopard","Lion","Llama","Lobster","Locust","Loris","Louse","Lyrebird","Magpie","Mallard","Manatee","Mandrill","Mantis","Marten","Meerkat","Mink","Mole","Mongoose","Monkey","Moose","Mosquito","Mouse","Mule","Narwhal","Newt","Nightingale","Octopus","Okapi","Opossum","Oryx","Ostrich","Otter","Owl","Oyster","Panther","Parrot","Partridge","Peafowl","Pelican","Penguin","Pheasant","Pig","Pigeon","Pony","Porcupine","Porpoise","Quail","Quelea","Quetzal","Rabbit","Raccoon","Rail","Ram","Rat","Raven","Red deer","Red panda","Reindeer","Rhinoceros","Rook","Salamander","Salmon","Sand Dollar","Sandpiper","Sardine","Scorpion","Seahorse","Seal","Shark","Sheep","Shrew","Skunk","Snail","Snake","Sparrow","Spider","Spoonbill","Squid","Squirrel","Starling","Stingray","Stinkbug","Stork","Swallow","Swan","Tapir","Tarsier","Termite","Tiger","Toad","Trout","Turkey","Turtle","Viper","Vulture","Wallaby","Walrus","Wasp","Weasel","Whale","Wildcat","Wolf","Wolverine","Wombat","Woodcock","Woodpecker","Worm","Wren","Yak","Zebra"
]



animArr = animArr.map(x => {
    return pluralize(x)
})

module.exports.adjArr = adjArr;
module.exports.animArr = animArr;
